run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - testifylint

linters-settings:
  gofmt:
    simplify: true
  testifylint:
    enable-all: true
